name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install modules
        run: yarn install

      - name: Run ESLint
        run: yarn eslint

      - name: Run Tests
        run: yarn test

      - name: Build
        run: yarn build
